AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
    Default: example-cfn-bucket-23338
Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName:
          !Ref BucketName

     
      